name: Test workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Name the CI log
        run: echo "First line of the test workflow"

      - name: Install composer dependencies
        run: composer install --ignore-platform-reqs

      - name: Copy ENV Laravel Configuration for CI
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate key
        run: php artisan key:generate

      - name: Run Unit test
        run: vendor/bin/phpunit
