name: Test workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Name the CI log
        run: echo "First line of the test workflow" && ls -la

      - name: Install composer dependencies
        run: cd ../ && composer install --ignore-platform-reqs

      - name: Run Unit test
        run: composer phpunit
